name: Rust

on:
  push:
    branches: [ corpus ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Get wasm-pack    
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Run tests
      run: wasm-pack test --node
    - name: Build
      run: wasm-pack build --release
    - name: Build web
      run: cd www && npm ci && npm run build
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        FOLDER: www/dist
        BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAN: true
